<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Content;
use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @method Content[] findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 * @method Content findOneBy(array $criteria, array $orderBy = null)
 * @method Content find($id, $lockMode = null, $lockVersion = null)
 */
class ContentRepository extends EntityRepository
{
}
