sub_app:
    resource: "@AppBundle/Controller/SiteController.php"
    type:     annotation
    prefix:   /
    host:     '{project_name}.%domain%'
    schemes:    [http]
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
    host:     '{project_name}.%domain%'
    schemes:    [http]
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    host:     '%domain%'
    defaults:
        domain: '%domain%'
    requirements:
        domain: '%domain%'

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login


facebook_login:
    path: /login/check_facebook

logout:
    path: /logout
