# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        hwi:
            id: hwi_oauth.user.provider.entity

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            logout_on_user_change: true
            oauth:
                resource_owners:
                    facebook: /login/check_facebook
                login_path: /login
                use_forward: false
                failure_path: /login
                default_target_path: /redirect_to_page
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity
            remember_me:
                secret:   '%secret%'
                lifetime: 604800
                path:     /
                domain:   ".%domain%"
            logout:
                path:   /logout
                target: /
                invalidate_session: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
